# Generated by Django 5.0.2 on 2024-02-24 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_name', models.CharField(max_length=100)),
                ('backend', models.URLField()),
                ('prometheus', models.URLField()),
                ('alertmanager', models.URLField()),
                ('grafana', models.URLField()),
            ],
        ),
    ]
